/* Created by Darren Otgaar on 2016/03/05. http://www.github.com/otgaard/zap */

#ifdef __APPLE__
//#define GLFW_INCLUDE_GLCOREARB
#endif //__APPLE__

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#define LOGGING_ENABLED
#include <tools/log.hpp>
#include <engine/shader.hpp>
#include <vector>
#include <engine/program.hpp>
#include <maths/mat4.hpp>
#include <maths/vec4.hpp>
#include <maths/vec3.hpp>
#include <maths/vec2.hpp>
#include <engine/buffer_format.hpp>
#include <maths/functions.hpp>

#include "engine/vertex_buffer.hpp"

static void on_error(int error, const char* description) {
    LOG_ERR("GLFW Error:", error, "Description:", description);
}

#define GLSL(src) "#version 330 core\n" #src

const char* vtx_src = GLSL(
    uniform mat4 proj_matrix;
    in vec2 position;

    void main() {
        gl_Position = proj_matrix*vec4(position.x, position.y, 0.0, 1.0);
    }
);

const char* frg_src = GLSL(
    out vec4 frag_colour;

    void main() {
        frag_colour = vec4(1.0, 0.0, 0.0, 1.0);
    }
);

using namespace zap::engine;

#include <engine/gl_api.hpp>
#include <engine/types.hpp>

template <typename FNC>
struct wave {
    constexpr static auto make_fnc(FNC fnc, float frequency, float amplitude, float phase) {
        return [=](float x) -> float {
            return amplitude*fnc(x*frequency + phase);
        };
    };
};

template <typename IT, typename FNC>
void sample(IT begin, IT end, float start, float stop, FNC fnc) {
    const auto samples = end - begin;
    const auto inc = (stop - start)/samples;
    for(auto it = begin; it != end; ++it) {
        it->position.x = start + inc * (it - begin);
        it->position.y = fnc(it->position.x);
    }
}

int main(int argc, char* argv[]) {
    glfwSetErrorCallback(::on_error);

    if(!glfwInit()) return -1;

    glfwWindowHint(GLFW_SAMPLES, 8);
    glfwWindowHint(GLFW_DEPTH_BITS, 24);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    auto window = glfwCreateWindow(1280, 768, "zap_example", nullptr, nullptr);
    if(!window) {
        LOG_ERR("Error creating window - terminating");
        glfwTerminate();
        return -1;
    }
    glfwMakeContextCurrent(window);

    glewExperimental = GL_TRUE;
    GLenum err = glewInit();
    if(err != GLEW_OK) {
        LOG("GLEW failed to initialise: ", glewGetErrorString(err));
        return -1;
    }
    LOG("Suppressing error generated by GLEW", glGetError());

    glClearColor(0.15f, 0.15f, 0.15f, 1.0f);
    glfwSwapInterval(1);

    glViewport(0, 0, 1280, 768);

    std::vector<shader_ptr> arr;
    arr.push_back(std::make_shared<shader>(shader_type::ST_VERTEX, vtx_src));
    arr.push_back(std::make_shared<shader>(shader_type::ST_FRAGMENT, frg_src));

    auto prog = std::make_shared<program>(std::move(arr));
    prog->link(true);
	gl_error_check();

    zap::maths::mat4<float> proj_matrix = {
        80/1280.f,      0.f, 0.f, 0.f,
        0.f,       80/768.f, 0.f, 0.f,
        0.f,            0.f, 2.f, 0.f,
        0.f,            0.f, 0.f, 1.f
    };

    prog->bind();
    auto loc = prog->uniform_location("proj_matrix");
    glUniformMatrix4fv(loc, 1, GL_FALSE, proj_matrix.data());
    prog->release();
    gl_error_check();

    using namespace zap::maths;
    using namespace zap::engine;

    vertex_buffer<pos3_t, buffer_usage::BU_STATIC_DRAW> frame;
    vertex_buffer<pos3_t, buffer_usage::BU_DYNAMIC_DRAW> graph;

    std::vector<pos3_t> box;
    box.push_back(pos3_t({{-10,-1,0}}));
    box.push_back(pos3_t({{10,-1,0}}));
    box.push_back(pos3_t({{10,1,0}}));
    box.push_back(pos3_t({{-10,1,0}}));

    GLuint frame_mesh;
    glGenVertexArrays(1, &frame_mesh);
    glBindVertexArray(frame_mesh);
    frame.allocate();
    frame.bind();
    frame.initialise(box);
    glBindVertexArray(0);
    gl_error_check();

    GLuint line_mesh;
    glGenVertexArrays(1, &line_mesh);
    glBindVertexArray(line_mesh);
    graph.allocate();
    graph.bind();
    graph.initialise(1000);
    glBindVertexArray(0);
    gl_error_check();

    float offset = 0.0f;
    constexpr float pi = zap::maths::PI;
    timer t;
    float prev = t.getf(), curr = t.getf();

    auto sin1hz = wave<decltype(sinf)>::make_fnc(sinf, 10, .5f, 0.f);
    auto sin3hz = wave<decltype(sinf)>::make_fnc(sinf, 30, .5f, 0.f);

    while(!glfwWindowShouldClose(window)) {
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
        prog->bind();

        glBindVertexArray(frame_mesh);
        glDrawArrays(GL_LINE_LOOP, 0, frame.vertex_count());
        glBindVertexArray(0);

        graph.bind();
        graph.map(buffer_access::BA_WRITE_ONLY);
        sample(graph.begin(), graph.end(), -pi, pi, [&offset, sin1hz, sin3hz](float x) { x+=offset; return sin3hz(x) + sin1hz(x); });
        graph.unmap();
        graph.release();

        glBindVertexArray(line_mesh);
        glDrawArrays(GL_LINE_STRIP, 0, graph.vertex_count());
        glBindVertexArray(0);

        offset += 5*(curr - prev);
        if(offset >= 2*pi) offset -= 2*pi;

        prev = curr;
        curr = t.getf();

        prog->release();
        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
